### ISSUE TITLE
Not finding fstar layer

### ISSUE THREAD

**Issue by nvesely** [kyoDralliam/fstar-layer#6]
Can't get this layer to run on a fresh Spacemacs install. From `*Messages*`:

```
(Spacemacs) Warning: Unknown layer fstar declared in dotfile.
```

Steps to reproduce:

1. Clone this repo to `~/.emacs.d/private/`.

2. Make only the following modifications to `~/.spacemacs`. I think `~/.emacs.d/private` path should be searched automatically for layers, but I added it after it `fstar` wasn't being found.

```
   dotspacemacs-configuration-layer-path '("~/.emacs.d/private/")
   ;; List of configuration layers to load.
   dotspacemacs-configuration-layers
   '(
     fstar
```

**Comment by Kazark** [comment]
When you cloned the repo, did you ensure the resulting directory was named `fstar`, not `fstar-layer`, as it would have been, by default? I hit that. After renaming the directory to `fstar`, I've got it working.

**Comment by nvesely** [comment]
@Kazark that worked, thanks.
